// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	chunking "nadir/internal/knowledge/chunking"

	mock "github.com/stretchr/testify/mock"
)

// MockChunker is an autogenerated mock type for the Chunker type
type MockChunker struct {
	mock.Mock
}

type MockChunker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChunker) EXPECT() *MockChunker_Expecter {
	return &MockChunker_Expecter{mock: &_m.Mock}
}

// Chunk provides a mock function with given fields: text, filePath
func (_m *MockChunker) Chunk(text string, filePath string) ([]chunking.Chunk, error) {
	ret := _m.Called(text, filePath)

	if len(ret) == 0 {
		panic("no return value specified for Chunk")
	}

	var r0 []chunking.Chunk
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]chunking.Chunk, error)); ok {
		return rf(text, filePath)
	}
	if rf, ok := ret.Get(0).(func(string, string) []chunking.Chunk); ok {
		r0 = rf(text, filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chunking.Chunk)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(text, filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChunker_Chunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chunk'
type MockChunker_Chunk_Call struct {
	*mock.Call
}

// Chunk is a helper method to define mock.On call
//   - text string
//   - filePath string
func (_e *MockChunker_Expecter) Chunk(text interface{}, filePath interface{}) *MockChunker_Chunk_Call {
	return &MockChunker_Chunk_Call{Call: _e.mock.On("Chunk", text, filePath)}
}

func (_c *MockChunker_Chunk_Call) Run(run func(text string, filePath string)) *MockChunker_Chunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockChunker_Chunk_Call) Return(_a0 []chunking.Chunk, _a1 error) *MockChunker_Chunk_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChunker_Chunk_Call) RunAndReturn(run func(string, string) ([]chunking.Chunk, error)) *MockChunker_Chunk_Call {
	_c.Call.Return(run)
	return _c
}

// ContextualText provides a mock function with given fields: c
func (_m *MockChunker) ContextualText(c chunking.Chunk) string {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ContextualText")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(chunking.Chunk) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockChunker_ContextualText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContextualText'
type MockChunker_ContextualText_Call struct {
	*mock.Call
}

// ContextualText is a helper method to define mock.On call
//   - c chunking.Chunk
func (_e *MockChunker_Expecter) ContextualText(c interface{}) *MockChunker_ContextualText_Call {
	return &MockChunker_ContextualText_Call{Call: _e.mock.On("ContextualText", c)}
}

func (_c *MockChunker_ContextualText_Call) Run(run func(c chunking.Chunk)) *MockChunker_ContextualText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(chunking.Chunk))
	})
	return _c
}

func (_c *MockChunker_ContextualText_Call) Return(_a0 string) *MockChunker_ContextualText_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChunker_ContextualText_Call) RunAndReturn(run func(chunking.Chunk) string) *MockChunker_ContextualText_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChunker creates a new instance of MockChunker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunker {
	mock := &MockChunker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
