// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	chat "nadir/internal/conversation/chat"

	mock "github.com/stretchr/testify/mock"
)

// MockChat is an autogenerated mock type for the Chat type
type MockChat struct {
	mock.Mock
}

type MockChat_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChat) EXPECT() *MockChat_Expecter {
	return &MockChat_Expecter{mock: &_m.Mock}
}

// CancelTurn provides a mock function with given fields: turnID
func (_m *MockChat) CancelTurn(turnID string) bool {
	ret := _m.Called(turnID)

	if len(ret) == 0 {
		panic("no return value specified for CancelTurn")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(turnID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockChat_CancelTurn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTurn'
type MockChat_CancelTurn_Call struct {
	*mock.Call
}

// CancelTurn is a helper method to define mock.On call
//   - turnID string
func (_e *MockChat_Expecter) CancelTurn(turnID interface{}) *MockChat_CancelTurn_Call {
	return &MockChat_CancelTurn_Call{Call: _e.mock.On("CancelTurn", turnID)}
}

func (_c *MockChat_CancelTurn_Call) Run(run func(turnID string)) *MockChat_CancelTurn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChat_CancelTurn_Call) Return(_a0 bool) *MockChat_CancelTurn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChat_CancelTurn_Call) RunAndReturn(run func(string) bool) *MockChat_CancelTurn_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllSessions provides a mock function with given fields: ctx
func (_m *MockChat) DeleteAllSessions(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChat_DeleteAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllSessions'
type MockChat_DeleteAllSessions_Call struct {
	*mock.Call
}

// DeleteAllSessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChat_Expecter) DeleteAllSessions(ctx interface{}) *MockChat_DeleteAllSessions_Call {
	return &MockChat_DeleteAllSessions_Call{Call: _e.mock.On("DeleteAllSessions", ctx)}
}

func (_c *MockChat_DeleteAllSessions_Call) Run(run func(ctx context.Context)) *MockChat_DeleteAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockChat_DeleteAllSessions_Call) Return(_a0 error) *MockChat_DeleteAllSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChat_DeleteAllSessions_Call) RunAndReturn(run func(context.Context) error) *MockChat_DeleteAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields: ctx, sessionID
func (_m *MockChat) DeleteSession(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChat_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockChat_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockChat_Expecter) DeleteSession(ctx interface{}, sessionID interface{}) *MockChat_DeleteSession_Call {
	return &MockChat_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionID)}
}

func (_c *MockChat_DeleteSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockChat_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockChat_DeleteSession_Call) Return(_a0 error) *MockChat_DeleteSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChat_DeleteSession_Call) RunAndReturn(run func(context.Context, string) error) *MockChat_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// StartTurn provides a mock function with given fields: ctx, req
func (_m *MockChat) StartTurn(ctx context.Context, req chat.Request) chat.Turn {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for StartTurn")
	}

	var r0 chat.Turn
	if rf, ok := ret.Get(0).(func(context.Context, chat.Request) chat.Turn); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(chat.Turn)
	}

	return r0
}

// MockChat_StartTurn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTurn'
type MockChat_StartTurn_Call struct {
	*mock.Call
}

// StartTurn is a helper method to define mock.On call
//   - ctx context.Context
//   - req chat.Request
func (_e *MockChat_Expecter) StartTurn(ctx interface{}, req interface{}) *MockChat_StartTurn_Call {
	return &MockChat_StartTurn_Call{Call: _e.mock.On("StartTurn", ctx, req)}
}

func (_c *MockChat_StartTurn_Call) Run(run func(ctx context.Context, req chat.Request)) *MockChat_StartTurn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(chat.Request))
	})
	return _c
}

func (_c *MockChat_StartTurn_Call) Return(_a0 chat.Turn) *MockChat_StartTurn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChat_StartTurn_Call) RunAndReturn(run func(context.Context, chat.Request) chat.Turn) *MockChat_StartTurn_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, turnID, since
func (_m *MockChat) Subscribe(ctx context.Context, turnID string, since int64) (<-chan chat.TurnEvent, func(), bool) {
	ret := _m.Called(ctx, turnID, since)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan chat.TurnEvent
	var r1 func()
	var r2 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (<-chan chat.TurnEvent, func(), bool)); ok {
		return rf(ctx, turnID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) <-chan chat.TurnEvent); ok {
		r0 = rf(ctx, turnID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan chat.TurnEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) func()); ok {
		r1 = rf(ctx, turnID, since)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64) bool); ok {
		r2 = rf(ctx, turnID, since)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockChat_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockChat_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - turnID string
//   - since int64
func (_e *MockChat_Expecter) Subscribe(ctx interface{}, turnID interface{}, since interface{}) *MockChat_Subscribe_Call {
	return &MockChat_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, turnID, since)}
}

func (_c *MockChat_Subscribe_Call) Run(run func(ctx context.Context, turnID string, since int64)) *MockChat_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockChat_Subscribe_Call) Return(_a0 <-chan chat.TurnEvent, _a1 func(), _a2 bool) *MockChat_Subscribe_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChat_Subscribe_Call) RunAndReturn(run func(context.Context, string, int64) (<-chan chat.TurnEvent, func(), bool)) *MockChat_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChat creates a new instance of MockChat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChat(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChat {
	mock := &MockChat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
