// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	search "nadir/internal/retrieval/search"

	mock "github.com/stretchr/testify/mock"
)

// MockRetriever is an autogenerated mock type for the Retriever type
type MockRetriever struct {
	mock.Mock
}

type MockRetriever_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRetriever) EXPECT() *MockRetriever_Expecter {
	return &MockRetriever_Expecter{mock: &_m.Mock}
}

// Query provides a mock function with given fields: ctx, request
func (_m *MockRetriever) Query(ctx context.Context, request search.Request) (search.Result, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 search.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, search.Request) (search.Result, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, search.Request) search.Result); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(search.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, search.Request) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRetriever_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockRetriever_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - request search.Request
func (_e *MockRetriever_Expecter) Query(ctx interface{}, request interface{}) *MockRetriever_Query_Call {
	return &MockRetriever_Query_Call{Call: _e.mock.On("Query", ctx, request)}
}

func (_c *MockRetriever_Query_Call) Run(run func(ctx context.Context, request search.Request)) *MockRetriever_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(search.Request))
	})
	return _c
}

func (_c *MockRetriever_Query_Call) Return(_a0 search.Result, _a1 error) *MockRetriever_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRetriever_Query_Call) RunAndReturn(run func(context.Context, search.Request) (search.Result, error)) *MockRetriever_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRetriever creates a new instance of MockRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRetriever {
	mock := &MockRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
