// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	rewriting "nadir/internal/retrieval/rewriting"

	mock "github.com/stretchr/testify/mock"
)

// MockRewriter is an autogenerated mock type for the Rewriter type
type MockRewriter struct {
	mock.Mock
}

type MockRewriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRewriter) EXPECT() *MockRewriter_Expecter {
	return &MockRewriter_Expecter{mock: &_m.Mock}
}

// Rewrite provides a mock function with given fields: ctx, turns, query
func (_m *MockRewriter) Rewrite(ctx context.Context, turns []rewriting.Turn, query string) (string, error) {
	ret := _m.Called(ctx, turns, query)

	if len(ret) == 0 {
		panic("no return value specified for Rewrite")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []rewriting.Turn, string) (string, error)); ok {
		return rf(ctx, turns, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []rewriting.Turn, string) string); ok {
		r0 = rf(ctx, turns, query)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []rewriting.Turn, string) error); ok {
		r1 = rf(ctx, turns, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRewriter_Rewrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rewrite'
type MockRewriter_Rewrite_Call struct {
	*mock.Call
}

// Rewrite is a helper method to define mock.On call
//   - ctx context.Context
//   - turns []rewriting.Turn
//   - query string
func (_e *MockRewriter_Expecter) Rewrite(ctx interface{}, turns interface{}, query interface{}) *MockRewriter_Rewrite_Call {
	return &MockRewriter_Rewrite_Call{Call: _e.mock.On("Rewrite", ctx, turns, query)}
}

func (_c *MockRewriter_Rewrite_Call) Run(run func(ctx context.Context, turns []rewriting.Turn, query string)) *MockRewriter_Rewrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]rewriting.Turn), args[2].(string))
	})
	return _c
}

func (_c *MockRewriter_Rewrite_Call) Return(_a0 string, _a1 error) *MockRewriter_Rewrite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRewriter_Rewrite_Call) RunAndReturn(run func(context.Context, []rewriting.Turn, string) (string, error)) *MockRewriter_Rewrite_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRewriter creates a new instance of MockRewriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRewriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRewriter {
	mock := &MockRewriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
