// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	history "nadir/internal/conversation/history"

	mock "github.com/stretchr/testify/mock"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// GetSession provides a mock function with given fields: ctx, sessionID
func (_m *MockReader) GetSession(ctx context.Context, sessionID string) (history.Session, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 history.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (history.Session, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) history.Session); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(history.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockReader_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockReader_Expecter) GetSession(ctx interface{}, sessionID interface{}) *MockReader_GetSession_Call {
	return &MockReader_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionID)}
}

func (_c *MockReader_GetSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockReader_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReader_GetSession_Call) Return(_a0 history.Session, _a1 error) *MockReader_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_GetSession_Call) RunAndReturn(run func(context.Context, string) (history.Session, error)) *MockReader_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function with given fields: ctx, limit
func (_m *MockReader) ListSessions(ctx context.Context, limit int) ([]history.Session, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []history.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]history.Session, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []history.Session); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]history.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockReader_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockReader_Expecter) ListSessions(ctx interface{}, limit interface{}) *MockReader_ListSessions_Call {
	return &MockReader_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx, limit)}
}

func (_c *MockReader_ListSessions_Call) Run(run func(ctx context.Context, limit int)) *MockReader_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockReader_ListSessions_Call) Return(_a0 []history.Session, _a1 error) *MockReader_ListSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_ListSessions_Call) RunAndReturn(run func(context.Context, int) ([]history.Session, error)) *MockReader_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ListTurns provides a mock function with given fields: ctx, sessionID
func (_m *MockReader) ListTurns(ctx context.Context, sessionID string) ([]history.Turn, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListTurns")
	}

	var r0 []history.Turn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]history.Turn, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []history.Turn); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]history.Turn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_ListTurns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTurns'
type MockReader_ListTurns_Call struct {
	*mock.Call
}

// ListTurns is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockReader_Expecter) ListTurns(ctx interface{}, sessionID interface{}) *MockReader_ListTurns_Call {
	return &MockReader_ListTurns_Call{Call: _e.mock.On("ListTurns", ctx, sessionID)}
}

func (_c *MockReader_ListTurns_Call) Run(run func(ctx context.Context, sessionID string)) *MockReader_ListTurns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReader_ListTurns_Call) Return(_a0 []history.Turn, _a1 error) *MockReader_ListTurns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_ListTurns_Call) RunAndReturn(run func(context.Context, string) ([]history.Turn, error)) *MockReader_ListTurns_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
