// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	indexing "nadir/internal/knowledge/indexing"

	mock "github.com/stretchr/testify/mock"
)

// MockIngest is an autogenerated mock type for the Ingest type
type MockIngest struct {
	mock.Mock
}

type MockIngest_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngest) EXPECT() *MockIngest_Expecter {
	return &MockIngest_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, files
func (_m *MockIngest) Run(ctx context.Context, files []indexing.UploadFile) (indexing.Result, error) {
	ret := _m.Called(ctx, files)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 indexing.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []indexing.UploadFile) (indexing.Result, error)); ok {
		return rf(ctx, files)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []indexing.UploadFile) indexing.Result); ok {
		r0 = rf(ctx, files)
	} else {
		r0 = ret.Get(0).(indexing.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []indexing.UploadFile) error); ok {
		r1 = rf(ctx, files)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIngest_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockIngest_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - files []indexing.UploadFile
func (_e *MockIngest_Expecter) Run(ctx interface{}, files interface{}) *MockIngest_Run_Call {
	return &MockIngest_Run_Call{Call: _e.mock.On("Run", ctx, files)}
}

func (_c *MockIngest_Run_Call) Run(run func(ctx context.Context, files []indexing.UploadFile)) *MockIngest_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]indexing.UploadFile))
	})
	return _c
}

func (_c *MockIngest_Run_Call) Return(_a0 indexing.Result, _a1 error) *MockIngest_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIngest_Run_Call) RunAndReturn(run func(context.Context, []indexing.UploadFile) (indexing.Result, error)) *MockIngest_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIngest creates a new instance of MockIngest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngest(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngest {
	mock := &MockIngest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
