// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	cache "nadir/internal/retrieval/cache"

	mock "github.com/stretchr/testify/mock"
)

// MockSemanticCache is an autogenerated mock type for the SemanticCache type
type MockSemanticCache struct {
	mock.Mock
}

type MockSemanticCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSemanticCache) EXPECT() *MockSemanticCache_Expecter {
	return &MockSemanticCache_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function with given fields: ctx
func (_m *MockSemanticCache) Clear(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSemanticCache_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockSemanticCache_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSemanticCache_Expecter) Clear(ctx interface{}) *MockSemanticCache_Clear_Call {
	return &MockSemanticCache_Clear_Call{Call: _e.mock.On("Clear", ctx)}
}

func (_c *MockSemanticCache_Clear_Call) Run(run func(ctx context.Context)) *MockSemanticCache_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSemanticCache_Clear_Call) Return(_a0 error) *MockSemanticCache_Clear_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSemanticCache_Clear_Call) RunAndReturn(run func(context.Context) error) *MockSemanticCache_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, query
func (_m *MockSemanticCache) Get(ctx context.Context, query string) ([]cache.Candidate, bool, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []cache.Candidate
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]cache.Candidate, bool, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []cache.Candidate); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cache.Candidate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSemanticCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSemanticCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockSemanticCache_Expecter) Get(ctx interface{}, query interface{}) *MockSemanticCache_Get_Call {
	return &MockSemanticCache_Get_Call{Call: _e.mock.On("Get", ctx, query)}
}

func (_c *MockSemanticCache_Get_Call) Run(run func(ctx context.Context, query string)) *MockSemanticCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSemanticCache_Get_Call) Return(_a0 []cache.Candidate, _a1 bool, _a2 error) *MockSemanticCache_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSemanticCache_Get_Call) RunAndReturn(run func(context.Context, string) ([]cache.Candidate, bool, error)) *MockSemanticCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, query, candidates
func (_m *MockSemanticCache) Set(ctx context.Context, query string, candidates []cache.Candidate) error {
	ret := _m.Called(ctx, query, candidates)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []cache.Candidate) error); ok {
		r0 = rf(ctx, query, candidates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSemanticCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSemanticCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - candidates []cache.Candidate
func (_e *MockSemanticCache_Expecter) Set(ctx interface{}, query interface{}, candidates interface{}) *MockSemanticCache_Set_Call {
	return &MockSemanticCache_Set_Call{Call: _e.mock.On("Set", ctx, query, candidates)}
}

func (_c *MockSemanticCache_Set_Call) Run(run func(ctx context.Context, query string, candidates []cache.Candidate)) *MockSemanticCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]cache.Candidate))
	})
	return _c
}

func (_c *MockSemanticCache_Set_Call) Return(_a0 error) *MockSemanticCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSemanticCache_Set_Call) RunAndReturn(run func(context.Context, string, []cache.Candidate) error) *MockSemanticCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSemanticCache creates a new instance of MockSemanticCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSemanticCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSemanticCache {
	mock := &MockSemanticCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
