// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEnricher is an autogenerated mock type for the Enricher type
type MockEnricher struct {
	mock.Mock
}

type MockEnricher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnricher) EXPECT() *MockEnricher_Expecter {
	return &MockEnricher_Expecter{mock: &_m.Mock}
}

// ContextualIntro provides a mock function with given fields: ctx, documentExcerpt, chunkText
func (_m *MockEnricher) ContextualIntro(ctx context.Context, documentExcerpt string, chunkText string) (string, error) {
	ret := _m.Called(ctx, documentExcerpt, chunkText)

	if len(ret) == 0 {
		panic("no return value specified for ContextualIntro")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, documentExcerpt, chunkText)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, documentExcerpt, chunkText)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, documentExcerpt, chunkText)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnricher_ContextualIntro_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContextualIntro'
type MockEnricher_ContextualIntro_Call struct {
	*mock.Call
}

// ContextualIntro is a helper method to define mock.On call
//   - ctx context.Context
//   - documentExcerpt string
//   - chunkText string
func (_e *MockEnricher_Expecter) ContextualIntro(ctx interface{}, documentExcerpt interface{}, chunkText interface{}) *MockEnricher_ContextualIntro_Call {
	return &MockEnricher_ContextualIntro_Call{Call: _e.mock.On("ContextualIntro", ctx, documentExcerpt, chunkText)}
}

func (_c *MockEnricher_ContextualIntro_Call) Run(run func(ctx context.Context, documentExcerpt string, chunkText string)) *MockEnricher_ContextualIntro_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEnricher_ContextualIntro_Call) Return(_a0 string, _a1 error) *MockEnricher_ContextualIntro_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEnricher_ContextualIntro_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockEnricher_ContextualIntro_Call {
	_c.Call.Return(run)
	return _c
}

// HypotheticalQuestions provides a mock function with given fields: ctx, header, text, n
func (_m *MockEnricher) HypotheticalQuestions(ctx context.Context, header string, text string, n int) ([]string, error) {
	ret := _m.Called(ctx, header, text, n)

	if len(ret) == 0 {
		panic("no return value specified for HypotheticalQuestions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) ([]string, error)); ok {
		return rf(ctx, header, text, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) []string); ok {
		r0 = rf(ctx, header, text, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, header, text, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnricher_HypotheticalQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HypotheticalQuestions'
type MockEnricher_HypotheticalQuestions_Call struct {
	*mock.Call
}

// HypotheticalQuestions is a helper method to define mock.On call
//   - ctx context.Context
//   - header string
//   - text string
//   - n int
func (_e *MockEnricher_Expecter) HypotheticalQuestions(ctx interface{}, header interface{}, text interface{}, n interface{}) *MockEnricher_HypotheticalQuestions_Call {
	return &MockEnricher_HypotheticalQuestions_Call{Call: _e.mock.On("HypotheticalQuestions", ctx, header, text, n)}
}

func (_c *MockEnricher_HypotheticalQuestions_Call) Run(run func(ctx context.Context, header string, text string, n int)) *MockEnricher_HypotheticalQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockEnricher_HypotheticalQuestions_Call) Return(_a0 []string, _a1 error) *MockEnricher_HypotheticalQuestions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEnricher_HypotheticalQuestions_Call) RunAndReturn(run func(context.Context, string, string, int) ([]string, error)) *MockEnricher_HypotheticalQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnricher creates a new instance of MockEnricher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnricher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnricher {
	mock := &MockEnricher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
